### PR TITLE
Add library path to LD_LIBRARY_PATH/PATH

### PR DESCRIPTION
**Pull request by mihails-strasuns**

### CODE REVIEW

**Comment by Cogitri** [comment]
Huh, https://github.com/Cogitri/corecollector/commit/4bb57e229b1bd18a101a134fc567fac45c216e11/checks?check_suite_id=383274348, is there a module for core I'm missing? :thinking:

**Comment by WebFreak001** [comment]
you can't just use the development branch because github actions assumes you committed node_modules, which is only done, with production dependency node_modules, on the release branches here (to avoid PR conflicts and such)

**Comment by mihails-strasuns** [comment]
Oh, sorry, forgot about that. Will add temporary commit to this branch later today with node_modules.

**Comment by mihails-strasuns** [comment]
Done

**Comment by Cogitri** [comment]
Thanks, I'll try again.

**Comment by Cogitri** [comment]
Seems to work: https://github.com/Cogitri/corecollector/commit/b9245b4b1d69404c8505d5945fe84248a249d330/checks?check_suite_id=383680171

Thank you!

**Comment by Cogitri** [comment]
(Do note I only test on Linux though)

**Pull request merged**
